### ISSUE TITLE
[Feature] Find movie commentary/reviews through YouTube API

### ISSUE THREAD

**Issue by CinmonTost** [COSC381-2023Fall/final-project-CinmonTost#3]
**User Story** 
As someone who loves watching movies and movies reviews, I would like to find movie reviews and commentaries through YouTube Data API so that I can get other opinions on the movie.

- Persona: someone who loves watching movies and movie reviews
- Feature: find movie reviews and commentaries
- Business value: the user can get other opinions on the movie

**Tasks**
- [x] Set up the YouTube API key in config.py
- [x] Write a method for searching the movie reviews/commentary (not an API method). The input should be a movie title, and the output should be a list of 10 movie reviews and commentaries about that movie. (There is no standard/perfect solution to it. Use the best method you can think of to get the review/commentary videos).
- [x] Add tests for the above method (make sure every statement is tested)
- [x] If needed, update the README.md for instructions on how to test the new method
- [x] Write an API method in the FastAPI app. The route should be: /moviereviews/{movie_name}. The API method should return a list of 10 review videos. The data structure of each review is listed below. 

    id: str
    title: str
    description: str

- [x] Add tests for the new API method (make sure every statement is tested)

**Comment by CinmonTost** [comment]
Finished everything
