### ISSUE TITLE
Issue 3: [feature] Get a full description of a movie review

### ISSUE THREAD

**Issue by AliAlJabur24** [COSC381-2023Fall/final-project-CinmonTost#5]
# User Story

As someone who loves getting movie reviews, I would like to see full descriptions of a movie review video before I open the video. In this way, I can get more information to decide whether I want to watch this review or not.

- **Persona:** someone who loves watching movies and movie reviews
- **Feature:** show a full description of a movie review video
- **Business value:** the user can get more information of a video before watching it

## Tasks

- [x] create a method to retrieve the full description of a video. The input is a video id, and the output is the description of the video.
  - **Hint:** instead of using the `youtube.search().list` method, try `youtube.videos().list`. More about this API can be found at: [YouTube Data API Videos List](https://developers.google.com/youtube/v3/docs/videos/list)
- [x] add tests for this method
- [x] create an API in the FastAPI app, the route should be `/descriptions/{video_id}`. The input is the video_id, the output is the complete description of the video.
- [x] add tests for this API
- [x] if needed, update the README file
